version: '3'
services:
  mysql:
    image: "mysql:8.0"
    volumes:
      - ./dbData:/var/lib/mysql
    environment:
      MYSQL_DATABASE: money_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  app:
    build: .
    tty: true
    volumes:
      - ./:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - mysql